http:
  routers:
    auth-service:
      rule: "Host(`hashirayaz.site`) && PathPrefix(`/api/auth`)"
      entryPoints:
        - websecure
      service: auth-service
      tls: {}

    container-service:
      rule: "Host(`hashirayaz.site`) && PathPrefix(`/api`)"
      entryPoints:
        - websecure
      service: container-service
      tls: {}

    frontend:
      rule: "Host(`hashirayaz.site`)"
      entryPoints:
        - websecure
      service: frontend
      middlewares:
        - spa-redirect
      tls: {}

  services:
    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth_service:5000"

    container-service:
      loadBalancer:
        servers:
          - url: "http://container_service:5001"

    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend_container:4173"

  middlewares:
    spa-redirect:
      errors:
        status:
          - "404"
        service: frontend
        query: "/index.html"
